In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import  seaborn as sns
import sklearn
%matplotlib inline


Reading The Dataset

In [ ]:
data=pd.read_csv('/content/data collection.csv')

Analyze the dataset

In [ ]:
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

Handling missing values

In [ ]:
data.isnull().any

<bound method NDFrame._add_numeric_operations.<locals>.any of      Serial No.  GRE Score  TOEFL Score  University Rating    SOP   LOR   \
0         False      False        False              False  False  False   
1         False      False        False              False  False  False   
2         False      False        False              False  False  False   
3         False      False        False              False  False  False   
4         False      False        False              False  False  False   
..          ...        ...          ...                ...    ...    ...   
395       False      False        False              False  False  False   
396       False      False        False              False  False  False   
397       False      False        False              False  False  False   
398       False      False        False              False  False  False   
399       False      False        False              False  False  False   

      CGPA  Research  Cha

Splitting dependent and independent columns

In [ ]:
x=data.iloc[:,0:7].values 
x

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   4.5 ,   9.65],
       [  2.  , 324.  , 107.  , ...,   4.  ,   4.5 ,   8.87],
       [  3.  , 316.  , 104.  , ...,   3.  ,   3.5 ,   8.  ],
       ...,
       [398.  , 330.  , 116.  , ...,   5.  ,   4.5 ,   9.45],
       [399.  , 312.  , 103.  , ...,   3.5 ,   4.  ,   8.78],
       [400.  , 333.  , 117.  , ...,   5.  ,   4.  ,   9.66]])

In [ ]:
y=data.iloc[:,7:].values
y

array([[1.  , 0.92],
       [1.  , 0.76],
       [1.  , 0.72],
       [1.  , 0.8 ],
       [0.  , 0.65],
       [1.  , 0.9 ],
       [1.  , 0.75],
       [0.  , 0.68],
       [0.  , 0.5 ],
       [0.  , 0.45],
       [1.  , 0.52],
       [1.  , 0.84],
       [1.  , 0.78],
       [1.  , 0.62],
       [1.  , 0.61],
       [0.  , 0.54],
       [0.  , 0.66],
       [1.  , 0.65],
       [0.  , 0.63],
       [0.  , 0.62],
       [1.  , 0.64],
       [0.  , 0.7 ],
       [1.  , 0.94],
       [1.  , 0.95],
       [1.  , 0.97],
       [1.  , 0.94],
       [0.  , 0.76],
       [1.  , 0.44],
       [0.  , 0.46],
       [0.  , 0.54],
       [1.  , 0.65],
       [1.  , 0.74],
       [1.  , 0.91],
       [1.  , 0.9 ],
       [1.  , 0.94],
       [1.  , 0.88],
       [0.  , 0.64],
       [0.  , 0.58],
       [0.  , 0.52],
       [0.  , 0.48],
       [1.  , 0.46],
       [1.  , 0.49],
       [1.  , 0.53],
       [0.  , 0.87],
       [1.  , 0.91],
       [1.  , 0.88],
       [1.  , 0.86],
       [0.  ,

In [ ]:
x.shape

(400, 7)

In [ ]:
y.shape

(400, 2)

Splitting the data into train and set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size = 0.2,random_state = 10)

In [ ]:
y_train=(y_train>0.5)
y_train

array([[ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ True, False],
       [False, False],
       [False,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [ True,  True],
       [False, False],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [ Tr

In [ ]:
y_test=(y_test>0.5)

Training and Testing the module

In [ ]:
!pip install -U scikit-learn


In [48]:
!pipinstall "scikit_learn==0.22.2.post1"

/bin/bash: pipinstall: command not found


In [50]:
from sklearn.linear_model.logistic import LogisticRegression
cls =LogisticRegression(random_state =0)
lr=cls.fit(x_Train,y_Train)
y=column_or_1d(warn=True)
y_pred=lr.predict(x_test)
y_pred

In [ ]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred) *100))
print("Recall score : %f" %(recall_score(y_test,y_pred) *100))
print("RoC score : %f\n" %(roc_auc_score(y_test,y_pred) *100))
print(confusion_matrix(y_test,y_pred))


Save The Model

In [ ]:
import pickle
pickle.dumb(lr,open('university.pkl','wb'))
model=pickle.load(open('university.pkl','rb'))


Model Evaluation

Save the model